
name: Deploy shiny app

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: rstudio/shiny-workflows/setup-r-package@v1
        with:
          packages: |
            renv
            posit-dev/r-shinylive
            sessioninfo

      - name: Find package dependencies
        shell: Rscript {0}
        id: packages
        run: |
          # Find package dependencies using {renv} and install with {pak}
          pak::pak(
            unique(renv::dependencies(".")$Package)
          )

      - name: Build site
        shell: Rscript {0}
        run: |
          shinylive::export(".", "site")

      - name: Deploy using gh-pages
        if: github.event_name != 'pull_request'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: site
